import canonicalLaneMathlib.AdmissibleClass
import DiscreteOperationalCalculusCanonicalLaneLean.DiscreteTimeEvolution
import DiscreteOperationalCalculusCanonicalLaneLean.DifferenceOperator
import DiscreteOperationalCalculusCanonicalLaneLean.DiscreteGreenFormula
import DiscreteOperationalCalculusCanonicalLaneLean.DiscreteLaplaceOperator
import DiscreteOperationalCalculusCanonicalLaneLean.DiscreteHeatEquation
import DiscreteOperationalCalculusCanonicalLaneLean.DiscreteConvolutionProduct

namespace HautevilleHouse
namespace DiscreteOperationalCalculusCanonicalLaneLean

def DiscreteOperationalCalculusClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem discrete_operational_calculus_endgame (A : AdmissibleClass) :
    DiscreteOperationalCalculusClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end DiscreteOperationalCalculusCanonicalLaneLean
end HautevilleHouse